---
name: AI Community Moderator

permissions:
  contents: read # To read community health files
  issues: write # To comment on and lock issues
  pull-requests: write # To comment on and lock PRs
  discussions: write # To moderate discussions (if used)
  models: read # To access GitHub Models for AI inference

"on":
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  moderate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      models: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Moderate with AI
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          severity-threshold: 5
          model: "openai/gpt-4.1-mini"
